#Friday-Auto-Player-Script.lua

loadstring(game:HttpGet("https://controlc.com/0910be9e"))() -- okay this not work then

loadstring(game:HttpGet("https://github.com/jdlshus1/Funky-Friday-Auto-Player-Script.lua/edit/main/README.md"), true)() --not work? np

loadstring(game:HttpGet(("https://github.com/jdlshus1/Funky-Friday-Auto-Player-Script.lua/edit/main/README.md"))()

--İF THİS NOT WORK CLİCK THİS LİNK AND PASTE SCRİPT https://controlc.com/0910be9e

--Good Games

--Thanks for use my script

--pass = autoplayerboi
